site_name: AIML documents
site_author: Ganesh kinkar Giri
site_description: AIML 
use_directory_urls: True

theme:
    name: material
nav:
  - Home: index.md
  - AIML:
    - Programing:
      - PYTHON: Programing/python.md
    - Statistic:
      - Descriptive Statistics:
        - Measures of Central Tendency:
          - Mean: Statistic/DescriptiveStatistics/Measures-of-Central-Tendency/Mean.md
          - Median: Statistic/DescriptiveStatistics/Measures-of-Central-Tendency/Median.md
          - Mode: Statistic/DescriptiveStatistics/Measures-of-Central-Tendency/Mode.md
        - Measures of Position (Relative Standing):
          - Percentiles: Statistic/DescriptiveStatistics/Measures-of-Position-Relative-Standing/Percentiles.md
          - Quartiles: Statistic/DescriptiveStatistics/Measures-of-Position-Relative-Standing/Quartiles.md
          - Deciles: Statistic/DescriptiveStatistics/Measures-of-Position-Relative-Standing/Deciles.md
          - Z-Score: Statistic/DescriptiveStatistics/Measures-of-Position-Relative-Standing/Z-Score.md
        - Shape of the Distribution:
          - Skewness: Statistic/DescriptiveStatistics/Shape-of-the-Distribution/Skewness.md
          - Kurtosis: Statistic/DescriptiveStatistics/Shape-of-the-Distribution/Kurtosis.md
        - Visualization Tools:
          - Histogram: Statistic/DescriptiveStatistics/Visualization-Tools/Histogram.md
          - Bar Chart: Statistic/DescriptiveStatistics/Visualization-Tools/BarChart.md
          - Pie Chart: Statistic/DescriptiveStatistics/Visualization-Tools/PieChart.md
          - Box Plot: Statistic/DescriptiveStatistics/Visualization-Tools/BoxPlot.md
          - Line Plot: Statistic/DescriptiveStatistics/Visualization-Tools/LinePlot.md
          - Dot Plot: Statistic/DescriptiveStatistics/Visualization-Tools/DotPlot.md
        - Measures of Dispersion (Variability):
          - Range: Statistic/DescriptiveStatistics/Measures-of-Dispersion/Range.md
          - Variance: Statistic/DescriptiveStatistics/Measures-of-Dispersion/Variance.md
          - Standard Deviation: Statistic/DescriptiveStatistics/Measures-of-Dispersion/StandardDeviation.md
          - Interquartile Range(IQR): Statistic/DescriptiveStatistics/Measures-of-Dispersion/InterquartileRange.md
          - Cofficient of Variation: Statistic/DescriptiveStatistics/Measures-of-Dispersion/CofficientVariation.md
      - Inferential Statistics:
        - Population and Sample:
          - Population: Statistic/InferentialStatistics/Population-and-Sample/Population.md
          - Sample: Statistic/InferentialStatistics/Population-and-Sample/Sample.md
          - Sampling Methods: Statistic/InferentialStatistics/Population-and-Sample/SamplingMethods.md
        - Estimation:
          - Point Estimation: Statistic/InferentialStatistics/Estimation/PointEstimation.md
          - Interval Estimation: Statistic/InferentialStatistics/Estimation/IntervalEstimation.md
          - Margin of Error: Statistic/InferentialStatistics/Estimation/MarginError.md
        - Regression and Correlation Analysis:
          - Linear Regression: Statistic/InferentialStatistics/Regression-and-Correlation-Analysis/LinearRegression.md
          - Logistic Regression: Statistic/InferentialStatistics/Regression-and-Correlation-Analysis/LogisticRegression.md
          - Multiple Regression: Statistic/InferentialStatistics/Regression-and-Correlation-Analysis/MultipleRegression.md
          - Correlation Coefficients: Statistic/InferentialStatistics/Regression-and-Correlation-Analysis/CorrelationCoefficients.md
        - Hypothesis Testing:
          - Null Hypothesis (H₀): Statistic/InferentialStatistics/Hypothesis-Testing/NullHypothesis.md
          - Alternative Hypothesis (H₁): Statistic/InferentialStatistics/Hypothesis-Testing/AlternativeHypothesis.md
          - Test Statistic: Statistic/InferentialStatistics/Hypothesis-Testing/TestStatistic.md
          - p-value: Statistic/InferentialStatistics/Hypothesis-Testing/pvalue.md
          - Significance Level (α): Statistic/InferentialStatistics/Hypothesis-Testing/SignificanceLevel.md
          - Type I Error (α): Statistic/InferentialStatistics/Hypothesis-Testing/TypeIError.md
          - Type II Error (β): Statistic/InferentialStatistics/Hypothesis-Testing/TypeIIError.md
          - Power of the Test: Statistic/InferentialStatistics/Hypothesis-Testing/PoweroftheTest.md
        - Parametric Tests:
          - t-test: Statistic/InferentialStatistics/Parametric-Tests/t-test.md
          - z-test: Statistic/InferentialStatistics/Parametric-Tests/z-test.md
          - ANOVA: Statistic/InferentialStatistics/Parametric-Tests/ANOVA.md
          - F-test: Statistic/InferentialStatistics/Parametric-Tests/F-test.md
        - Non-Parametric Tests:
          - Mann-Whitney U: Statistic/InferentialStatistics/Non-Parametric-Tests/Mann-WhitneyU.md
          - Kruskal-Wallis: Statistic/InferentialStatistics/Non-Parametric-Tests/Kruskal-Wallis.md
          - Wilcoxon: Statistic/InferentialStatistics/Non-Parametric-Tests/Wilcoxon.md
          - Chi-square: Statistic/InferentialStatistics/Non-Parametric-Tests/Chi-square.md
        - Resampling Methods:
          - Bootstrapping: Statistic/InferentialStatistics/Resampling-Methods/Bootstrapping.md
          - Jackknife: Statistic/InferentialStatistics/Resampling-Methods/Jackknife.md
        - Analysis of Variance (ANOVA):
          - One-way ANOVA: Statistic/InferentialStatistics/ANOVA/One-way-ANOVA.md
          - Two-way ANOVA: Statistic/InferentialStatistics/ANOVA/Two-way-ANOVA.md
          - Post-hoc Tests: Statistic/InferentialStatistics/ANOVA/Post-hoc-Tests.md
        - Probability Theory:
          - Probability Distributions: Statistic/InferentialStatistics/Probability-Theory/ProbabilityDistributions.md
          - Central Limit Theorem: Statistic/InferentialStatistics/Probability-Theory/CentralLimitTheorem.md
          - Bayesian Inference: Statistic/InferentialStatistics/Probability-Theory/BayesianInference.md
      - Time Series:
        - Trend: Statistic/TimeSeries/Trend.md
        - Seasonality: Statistic/TimeSeries/Seasonality.md
        - Cyclic: Statistic/TimeSeries/Cyclic.md
        - Irregular/Noise: Statistic/TimeSeries/Noise.md
        - Stationarity: Statistic/TimeSeries/Stationarity.md
        - Non-stationary: Statistic/TimeSeries/Non-stationary.md
        - Autocorrelation: Statistic/TimeSeries/Autocorrelation.md
        - Lag: Statistic/TimeSeries/Lag.md
        - Moving Averages: Statistic/TimeSeries/MovingAverages.md
        - Holt-Winters Method: Statistic/TimeSeries/Holt-Winters.md
        - Additive: Statistic/TimeSeries/Additive.md
        - Multiplicative: Statistic/TimeSeries/Multiplicative.md
        - AR (Auto Regression): Statistic/TimeSeries/AR.md
        - ARIMA: Statistic/TimeSeries/ARIMA.md
        - Arimax: Statistic/TimeSeries/Arimax.md
        - Sarimax: Statistic/TimeSeries/Sarimax.md
        - Smoothing: Statistic/TimeSeries/Smoothing.md
        - Automated Forecasting: Statistic/TimeSeries/AutomatedForecasting.md
        - Automated Time Series: Statistic/TimeSeries/AutomatedTimeSeries.md
        - Uni, Bi and Multivariate: Statistic/TimeSeries/Multivariate.md
      - Metrics Evaluation: Statistic/metrics.md
      - Time Series Old: Statistic/timeseries.md
      - Statistic Details: Statistic/statistic-details.md
    - Data manipulation and analysis:
      - PANDAS: Data-manipulation-and-analysis/data-manipulation-analysis.md
    - Data Processing:
      - Basic SQL: Data-processing/sql.md
      - Using SQL for Data Science: Data-processing/sql-datascience.md
      - Unstructured Data: Data-processing/unstructured-data.md
      - Exploratory Data Analysis(EDA): Data-processing/exploratory-data-analysis.md
      - Building ML Models on Text Data: Data-processing/building-ml-models-on-text-data.md
    - Databases:
      - PostgreSQL: Databases/PostgreSQL.md
      - MySQL: Databases/MySQL.md
      - MongoDB: Databases/MongoDB.md
    - Machine Learning:
      - Overview: MachineLearning/Overview.md
      - Supervised Learning:
        - Overview: MachineLearning/SupervisedLearning/Overview.md
        - Regression: MachineLearning/SupervisedLearning/Regression.md
        - Classification: MachineLearning/SupervisedLearning/Classification.md
        - Cross Validation: MachineLearning/SupervisedLearning/CrossValidation.md
        - Hyperparameter Tuning: MachineLearning/SupervisedLearning/HyperparameterTuning.md
        - Tuning decision threshold: MachineLearning/SupervisedLearning/TuningDecisionThreshold.md
        - Regression Models:
          - Simple Linear Regression: MachineLearning/SupervisedLearning/RegressionModels/SimpleLinearRegression.md
          - Multiple Linear Regression: MachineLearning/SupervisedLearning/RegressionModels/MultipleLinearRegression.md
          - Polynomial Regression: MachineLearning/SupervisedLearning/RegressionModels/PolynomialRegression.md
          - Ridge & Lasso Regression: MachineLearning/SupervisedLearning/RegressionModels/RidgeLassoRegression.md
          - Support Vector Regression (SVR): MachineLearning/SupervisedLearning/RegressionModels/SupportVectorRegression.md
          - Decision Tree Regression: MachineLearning/SupervisedLearning/RegressionModels/DecisionTreeRegression.md
          - Random Forest Regression: MachineLearning/SupervisedLearning/RegressionModels/RandomForestRegression.md
        - Linear Classification Models:
          - Logistic Regression: MachineLearning/SupervisedLearning/LinearClassificationModels/LogisticRegression.md
          - Support Vector Machines: MachineLearning/SupervisedLearning/LinearClassificationModels/SupportVectorMachines.md
          - Single-layer Perceptron: MachineLearning/SupervisedLearning/LinearClassificationModels/SinglelayerPerceptron.md
          - Stochastic Gradient Descent (SGD): MachineLearning/SupervisedLearning/LinearClassificationModels/StochasticGradientDescent.md
        - Non-linear Classification Models:
          - Decision Tree Classification: MachineLearning/SupervisedLearning/NonlinearClassificationModels/DecisionTreeClassification.md
          - K-Nearest Neighbours: MachineLearning/SupervisedLearning/NonlinearClassificationModels/KNearestNeighbours.md
          - Naive Bayes: MachineLearning/SupervisedLearning/NonlinearClassificationModels/NaiveBayes.md
          - Random Forests: MachineLearning/SupervisedLearning/NonlinearClassificationModels/RandomForests.md
          - AdaBoost: MachineLearning/SupervisedLearning/NonlinearClassificationModels/AdaBoost.md
          - Bagging Classifier: MachineLearning/SupervisedLearning/NonlinearClassificationModels/BaggingClassifier.md
          - Ensemble learning classifiers: MachineLearning/SupervisedLearning/NonlinearClassificationModels/Ensemblelearningclassifiers.md
          - Kernel SVM: MachineLearning/SupervisedLearning/NonlinearClassificationModels/KernelSVM.md
      - Unsupervised Learning:
        - Overview: MachineLearning/UnsupervisedLearning/overview.md
        - Clustering: MachineLearning/UnsupervisedLearning/Clustering.md
        - Principal Component Analysis(PCA): MachineLearning/UnsupervisedLearning/Pca.md
      - Reinforcement Learning: 
        - Overview: MachineLearning/ReinforcementLearning/ReinforcementLearning.md
    - Linear Algebra:
      - Overview: LinearAlgebra/Overview.md
    - Deep Learning:
      - Overview: DeepLearning/Overview.md
      - Vanishing and Exploding Gradients Problems: DeepLearning/Vanishing.md
      - Components of Neural Networks:
        - Layers in Neural Networks: DeepLearning/Components/LayersNeuralNetworks.md
        - Weights and Biases: DeepLearning/Components/WeightsBiases.md
        - Forward Propagation: DeepLearning/Components/ForwardPropagation.md
        - Activation Functions: DeepLearning/Components/ActivationFunctions.md
        - Loss Functions: DeepLearning/Components/LossFunctions.md
        - Backpropagation: DeepLearning/Components/Backpropagation.md
        - Learning Rate: DeepLearning/Components/LearningRate.md
      - Optimization Algorithm:
        - Gradient Descent: DeepLearning/OptimizationAlgorithm/GradientDescent.md
        - Stochastic Gradient Descent (SGD): DeepLearning/OptimizationAlgorithm/SGD.md
        - Adam (Adaptive Moment Estimation): DeepLearning/OptimizationAlgorithm/Adam.md
        - Batch Normalization: DeepLearning/OptimizationAlgorithm/BatchNormalization.md
        - Mini-batch Gradient Descent: DeepLearning/OptimizationAlgorithm/Mini-batch-GD.md
        - Momentum-based Gradient Optimizer: DeepLearning/OptimizationAlgorithm/Momentum-based-GO.md
        - Adagrad Optimizer: DeepLearning/OptimizationAlgorithm/AdagradOptimizer.md
        - RMSProp Optimizer: DeepLearning/OptimizationAlgorithm/RMSPropOptimizer.md
      - Models:
        - Feedforward Neural Network (FNN): DeepLearning/Models/FNN.md
        - Recurrent Neural Network (RNN):
          - Recurrent Neural Network (RNN): DeepLearning/Models/RNN.md 
          - LSTM (Long Short-Term Memory): DeepLearning/Models/LSTM.md
          - GRU (Gated Recurrent Unit): DeepLearning/Models/GRU.md
        - Convolutional Neural Network (CNN): DeepLearning/Models/CNN.md
        - Radial Basis Function Network (RBFN): DeepLearning/Models/RBFN.md
        - Computer Vision: DeepLearning/Models/ComputerVision.md
        - Generative Adversarial Networks (GANs): DeepLearning/Models/GANs.md
        - Transformer Networks: DeepLearning/Models/Transformer.md
        - Autoencoders: DeepLearning/Models/Autoencoders.md
        - Self-Organizing Maps (SOM): DeepLearning/Models/SOM.md
    - Natural Language Processing(NLP): 
      - Overview: NLP/overview.md
      - NLP Details: NLP/nlpdetails.md
    - Computer Vision:
      - Overview: Computer-Vision/Overview.md
      - Traditional CV (Before deep learning):
        - Edge detection: Computer-Vision/Edge-detection.md
        - Feature extraction: Computer-Vision/Feature-extraction.md
        - Image filtering: Computer-Vision/Image-filtering.md
        - Template matching: Computer-Vision/Template-matching.md
        - Optical flow: Computer-Vision/Optical-flow.md
        - Histogram analysis: Computer-Vision/Histogram-analysis.md
        - Rule-based vision systems: Computer-Vision/Rule-based-vision-systems.md
      - Modern CV (Deep learning–based):
        - CNNs: Computer-Vision/CNNs.md
        - Vision Transformers (ViT): Computer-Vision/ViT.md
        - YOLO: Computer-Vision/YOLO.md
        - Faster R-CNN: Computer-Vision/Faster-R-CNN.md
        - Mask R-CNN: Computer-Vision/Mask-R-CNN.md
        - Diffusion models (for vision generation): Computer-Vision/Diffusion-models.md
      - Common Computer Vision tasks:
        - Image classification: Computer-Vision/Image-classification.md
        - Object detection: Computer-Vision/Object-detection.md
        - Face recognition: Computer-Vision/Face-recognition.md
        - OCR (text from images): Computer-Vision/OCR.md
        - Medical imaging analysis: Computer-Vision/Medical-imaging-analysis.md
        - Autonomous driving vision: Computer-Vision/Autonomous-driving-vision.md
        - Video analytics: Computer-Vision/Video-analytics.md
        - Industrial inspection: Computer-Vision/Industrial-inspection.md
      - OpenCV: OpenCV/OpenCV.md
    - Retrieval-Augmented Generation(RAG):
      - RAG: RAG/rag.md
    - AI agents:
      - AI agents: AIagents/aiagents.md
    - Agentic AI:
      - Framework: AgenticAI/framework.md
      - Design Patterns: AgenticAI/design-patterns.md
      - general: AgenticAI/general.md
      - Overview: AgenticAI/overview.md
      - crewai: AgenticAI/crewai.md
      - LangGraph: 
        - Overview: AgenticAI/LangGraph/LangGraph.md
        - LangGraph Graph API: AgenticAI/LangGraph/LangGraphDetails.md
        - Subgraphs: AgenticAI/LangGraph/Subgraphs.md
        - Interrupts: AgenticAI/LangGraph/Interrupts.md
        - Time travel: AgenticAI/LangGraph/time-travel.md
        - LangGraph runtime: AgenticAI/LangGraph/LangGraph-runtime.md
        - Durable execution: AgenticAI/LangGraph/Durable-execution.md
        - Install:  AgenticAI/LangGraph/Install.md
        - Graph API: AgenticAI/LangGraph/graph-api.md
        - Functional API: AgenticAI/LangGraph/functional-api.md
        - Run local server: AgenticAI/LangGraph/local-server.md
        - Workflows: AgenticAI/LangGraph/workflows.md
        - Agents: AgenticAI/LangGraph/agents.md
        - Persistence: AgenticAI/LangGraph/persistence.md
        - Memory: AgenticAI/LangGraph/memory.md
        - Streaming: AgenticAI/LangGraph/streaming.md
        - Interrupts: AgenticAI/LangGraph/interrupts.md
        - Graph: AgenticAI/LangGraph/graph.md
        - Node: AgenticAI/LangGraph/node.md
        - Edge: AgenticAI/LangGraph/edge.md
      - AutoGen: AgenticAI/AutoGen.md
      - AWS: AgenticAI/aws.md
      - AZURE: 
        - Overview: AgenticAI/AZURE/azure.md
        - Azure OpenAI Foundry models: AgenticAI/AZURE/azure-openai-foundry-modelsure.md
      - Agent Development Kit:
        - ADK : AgenticAI/GCP/adk.md
        - Agents: AgenticAI/GCP/Agents.md
        - Tools: AgenticAI/GCP/Tools.md
        - Tools: AgenticAI/GCP/a2a.md
    - Agent to Agent(A2A):
      - A2A: A2A/a2a.md
    - Temporal:
      - Overview: Temporal/temporal-overview.md
      - Setup: Temporal/setup.md
      - Core application: Temporal/core-application.md
      - Temporal Client: Temporal/Temporal-client.md
    - MCPModel Context Protocol(MCP):
      - MCP: MCP/mcp.md
    - Vector Databases:
      - PgVector: VectorDatabases/PgVector.md
      - OpenSearch: VectorDatabases/OpenSearch.md
    - Graph Databases:
      - neo4j setup: GraphDatabases/neo4j-setup.md
      - neo4j Cypher: GraphDatabases/neo4j-cypher.md
    - Models Details information:
      - Ollama: Models/Ollama.md
    - Note Book:
      - All Notebook: Notebook/allnotebook.md
    - Pypi Library:
      - Pypi Library Details: Pypi/Pypi-lib-details.md

#theme: readthedocs
theme:
    #name: material
    name: readthedocs
    #features:
    #    - toc.integrate
    #    - navigation.indexes
    #    - content.tabs.link
    #icon:
    #    repo: fontawesome/brands/github-alt

extra_css: [css/extra.css]
markdown_extensions:
   - admonition
   - codehilite
   - toc:
        toc_depth: 3
        permalink: "#"
   - tables        
use_directory_urls: false
plugins:
    - search
    - git-revision-date-localized
    - git-authors
    #- mkdocs-jupyter
